### PR TITLE
UX-7 add new color picker to courses

### PR DESCRIPTION
**Pull request by dominikbruechner**
- to restrict selectable colors for future color palette features
- default #ACACAC (other server PR reflects to server model)
- it's no beauty but works for now till the bigger rework with onboarding happens...
screenshot 2018-12-12 at 16 56 10

### CODE REVIEW

**Comment by janrenz** [comment]
And the yellow must take  care that the the text is Black for accessibility

**Comment by dominikbruechner** [comment]
> And the yellow must take care that the the text is Black for accessibility

will take care of that with course card rework, right now it has shadows which makes it acceptable... and a major improvement, as before every color was possible

**Comment by dominikbruechner** [comment]
screenshot 2018-12-12 at 18 33 32

Got the name back in real quick because of open PR and we have no more name on the platform right now

**Comment by schurigh** [comment]
@dominikbruechner If it looks like on your screenshot, spacing should get fixed, looks weird, doesn't it?

**Comment by dominikbruechner** [comment]
> @dominikbruechner If it looks like on your screenshot, spacing should get fixed, looks weird, doesn't it?

agreed, and optimised.
screenshot 2018-12-13 at 12 16 29

**Pull request merged**
