### PR TITLE
icons of 18 endings

### PR DESCRIPTION
**Pull request by Langleu**
pasted image at 2017_06_09 11_46 am

### CODE REVIEW

**Comment by jprberlin** [comment]
What will be the generic icon?

**Comment by Langleu** [comment]
currently the same as now.
As I'm limited due to OS restrictions you could come up with one in the same style.

**Comment by jprberlin** [comment]
Ok i will take care, so i will merge this once Travis is done

**Comment by pinussilvestrus** [comment]
[Icons für Dateitypen](https://trello.com/c/9YtBAtGf/568-icons-f%C3%BCr-dateitypen)

**Pull request merged**
