### PR TITLE
SC-159-multifile-upload

### PR DESCRIPTION
**Pull request by Langleu**
Folder upload via Drag & Drop.

Empty folders are not being uploaded as dropzone doesn't recognize them as file.

### CODE REVIEW

**Comment by schurigh** [comment]
@janrenz @Langleu 
If you don't have any concerns about that, feel free to merge right away.

**Comment by Langleu** [comment]
@schurigh maybe a blacklist for typical files? But ignoring hidden files in general might not be possible?
I did not look further into dropzone, but do they give you a flag that says hidden? Otherwise how do you know that a file is hidden if it only has a system flag?

**Comment by Langleu** [comment]
@schurigh @janrenz 
how about a blacklist containing all of those:
https://www.gitignore.io/api/linux,macos,windows

**Comment by janrenz** [comment]
Whats the behaviour of nexcloud or seafile & Co ..

**Comment by schurigh** [comment]
@Langleu I like this one: https://www.gitignore.io/api/linux,macos,windows - This might solve the most common "problems".
@janrenz I tested Dropbox: .lnk files were ignored, error with desktop.ini, all other files (hidden and system as well) were uploaded

**Comment by schurigh** [comment]
So I'll merge this one as folder upload is successfully done, let's do upload exceptions in another ticket/PR.

**Pull request merged**
