### PR TITLE
use polling for gulp watch

### PR DESCRIPTION
**Pull request by dominikglandorf**
This fixes the not working gulp rebuild after file changes in the docker containerion Docker for Windows.

### CODE REVIEW

**Comment by adrianjost** [comment]
still needed? There isn't any gulp watch anymore
https://github.com/schul-cloud/schulcloud-client/pull/518

**Comment by janrenz** [comment]
ping

**Comment by kremer-io** [comment]
I think this PR can be closed. @dominikglandorf ?

**Comment by pinussilvestrus** [comment]
I think this can be closed now

**Pull request closed without merging**
