### PR TITLE
Fingerprinted assets, needs to be tested

### PR DESCRIPTION
**Pull request by janrenz**
Works only in prod env

### CODE REVIEW

**Comment by janrenz** [comment]
@tofixx Please check the impact of this on the current offline state

**Comment by adrianjost** [comment]
I can't get it set up
image

**Comment by tofixx** [comment]
however got that error later, is it possible to find out where that was thrown?
```
TypeError: Parameter "url" must be a string, not object
   at Url.parse (url.js:103:11)
   at Object.urlParse [as parse] (url.js:97:13)
   at Object.furl (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/static-expiry/index.js:232:23)
   at eval (eval at createFunctionContext (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:10:66)
   at prog (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
   at Object.block (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars-layouts/index.js:173:5)
   at Object.eval [as main] (eval at createFunctionContext (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:9:72)
   at main (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
   at ret (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
   at ret (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
   at Object.extend (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars-layouts/index.js:132:11)
   at eval (eval at createFunctionContext (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:92)
   at Object.prog [as inverse] (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
   at Object.<anonymous> (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)
   at Object.eval [as main] (eval at createFunctionContext (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:35)
   at main (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
   at ret (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
   at ret (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
   at /Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars-wax/src/handlebars-wax.js:216:10
   at HandlebarsWax.engine (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/handlebars-wax/src/handlebars-wax.js:232:39)
   at View.render (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/express/lib/view.js:126:8)
   at tryRender (/Users/tobias/Documents/GitHub/schulcloud-client/node_modules/express/lib/application.js:639:10)
```

**Comment by tofixx** [comment]
the furl takes the second argument if enabled, but there is a wrong object in parameter given:
image

**Comment by tofixx** [comment]
solved issue with https://www.npmjs.com/package/@tofixx/static-expiry next questions:
[] how to replace links in css and js files

**Pull request closed without merging**
