### PR TITLE
Onboarding Course Creation Wizard

### PR DESCRIPTION
**Pull request by dominikbruechner**
Most important change: Removed Course Description Input (still existing in Edit Course)
Other:
- Form elements have no autocomplete
- Times can be selected now from 6:00 - 22:00, with a preset of 8:00

Screenshot 2019-03-18 at 15 34 50
Screenshot 2019-03-18 at 15 35 02
Screenshot 2019-03-18 at 16 00 59

### CODE REVIEW

**Comment by janrenz** [comment]
Didn't we discussed linked the last 3  CTAs (Themen anlegen, ...). And then I would name the Button Nein, Danke  zurück zur Kursübersicht. And what about "Noch ein Kurs anlegen" Choice ...

**Comment by dominikbruechner** [comment]
> Didn't we discussed linked the last 3 CTAs (Themen anlegen, ...). And then I would name the Button Nein, Danke zurück zur Kursübersicht. And what about "Noch ein Kurs anlegen" Choice ...

I decided against the 3 CTAs, because the user would get confused with the interface, and he is still in discovery mode at this point.

'noch ein Kurs' I forgot, going to check how it would work out

**Comment by janrenz** [comment]
maybe link it without visually indicating its a link, or roll it out and watch some heat maps

**Comment by janrenz** [comment]
Maybe unify wording of Mitglieder and Teilnehmer?

**Comment by dominikbruechner** [comment]
> Maybe unify wording of Mitglieder and Teilnehmer?

done

**Comment by dominikbruechner** [comment]
> maybe link it without visually indicating its a link, or roll it out and watch some heat maps

going to check it. I am really worrying that this would confuse the user. In the user tests nobody tried to click or was interested in having a shortcut... Going to put heatmap in place

**Pull request merged**
