### PR TITLE
Sc 3560 /homework/ homeworkid

### PR DESCRIPTION
**Pull request by abralurrahman**
# I have temporarily adjusted the base of this PR to better recognize the new changes. Please switch back to develop before merging!

- [ ] depends on #1702 
- [x] Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-3560

### CODE REVIEW

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 39
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5313806&bid=17391441)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 39
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5313806&bid=17391441)

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 5
- Added 39
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5313806&bid=17391441)

**Comment by CeEv** [comment]
How is the status of this PR?

**Pull request merged**
