### PR TITLE
SC-161-upgrade-webcomponents

### PR DESCRIPTION
**Pull request by malcm**
necessary webcomponents of m.e.i.n.e.l and video player are not compatible. Change in video-player and or m.e.i.n.e.l would be necessary (won't fix)

@janrenz  Possible update of video-player to version 2.2.2 (also would use webcomponents-bundle.js and fix this issue). But gulp building process destroy file video-player.js. Any suggestion?

### CODE REVIEW

**Comment by schurigh** [comment]
still WIP?

**Comment by janrenz** [comment]
move it to a vendor dir and exlude this from gulp

**Comment by malcm** [comment]
it was already in vendor before. So I introduced vendor-optimized. Maybe we can also have it in vendor and exclude vendor files by default for JS-optimization

**Comment by janrenz** [comment]
@schurigh please review and test, lgtm

**Comment by janrenz** [comment]
will be part of [WIP] Tobias/local vendors added

**Comment by adrianjost** [comment]
@janrenz @tofixx It's already merged right?

**Comment by tofixx** [comment]
> @janrenz @tofixx It's already merged right?

we have already merged the vendor-optimized task, yes.

**Comment by adrianjost** [comment]
then I'm gonna close this.

**Comment by malcm** [comment]
Adds missing video-Player update to version 2.2.2
Adds missing update for m.e.i.n.e.l
Adds Digital-Gipfel video to about page @ViviHPI 
Can be merged if this PR https://github.com/openHPI/video-player/pull/69 is accepted and the new video-player version 2.2.4 is added ... fixes SC-673 @janrenz

**Comment by janrenz** [comment]
69 is merged

**Comment by malcm** [comment]
@schurigh Review and merge?

**Pull request merged**
