### PR TITLE
Tobias/local vendors added

### PR DESCRIPTION
**Pull request by tofixx**
moved external ressources to local vendors directory

### CODE REVIEW

**Comment by tofixx** [comment]
however, gulp seems to not copy all files using watch

**Comment by janrenz** [comment]
vendor stuff should not be monitored by gulp watch. I think there is already some code or a PR adressing this. Also do we take crae that those librariers are only loaded where needed?

**Comment by tofixx** [comment]
ok. however the library is always imported when logged in

**Comment by janrenz** [comment]
i think it only need to be loaded on pages where the rich editor is used. The next iteration of the editor should support lazy loading ...

**Comment by adrianjost** [comment]
@tofixx It's working now. But do you have any ideas what we can do to speed up the process? gulp is running for a minute in my machine to build mathjax. For local development it's okay because we are caching, but the docker build time for our production server will increase a lot I think. And as far as I understand docker, we are running gulp on every restart?
@janrenz could this be a problem?

**Comment by janrenz** [comment]
No, gulp is just beeing used on build time, i refactored this a while ago

**Comment by Michael-Janke** [comment]
> @tofixx It's working now. But do you have any ideas what we can do to speed up the process? gulp is running for a minute in my machine to build mathjax. For local development it's okay because we are caching, but the docker build time for our production server will increase a lot I think. And as far as I understand docker, we are running gulp on every restart?
> @janrenz could this be a problem?

using webpack 😄 
it supports incremental builds, multi threading and bundling by design.
and it helps to only include things you really need. (And use npm instead of hard copies)

To be fair, also gulp4 is faster than gulp3

**Comment by tofixx** [comment]
@Michael-Janke the target of this pr was to move external vendors to a local path. Feel free to open a new pr that focuses on optimization of gulp.

**Comment by malcm** [comment]
@janrenz @tofixx I just reconized that the PR #795 was closed since this PR should include all changes. But it misses updating the video-player from version 1.3.2 to 2.2.2 and also misses updating m.e.i.n.e.l
Do you add this @tofixx or should I do it?

**Comment by malcm** [comment]
ok. I just didn't got why #795 was closed if it was not completly added here. I will take care of it in the upcoming days

**Comment by adrianjost** [comment]
Sorry @malcm I just overlooked these changes.

**Pull request merged**
