### PR TITLE
changed default view for calendar

### PR DESCRIPTION
**Pull request by dominikbruechner**
* changed page load transition

### CODE REVIEW

**Comment by adrianjost** [comment]
Auf der Seite gibts nen 404:
http://localhost:3100/styles/lib/toggle/bootstrap-toogle.min.css

**Comment by janrenz** [comment]
Screenshot?

**Comment by adrianjost** [comment]
image

**Comment by schurigh** [comment]
Don't we wanna hide some hours to fit all in a non-scrollable window? 6-22 would fit on a full-screen 24" without scrollbar.

**Comment by janrenz** [comment]
7-20 should be fine, or?

**Comment by janrenz** [comment]
Or can we make the height dynamic

**Pull request merged**
