### PR TITLE
remove additional parameters from url

### PR DESCRIPTION
**Pull request by tofixx**
optimized cleanup for analytics logging

### CODE REVIEW

**Comment by konstantin-sc** [comment]
Requeste mal einen einen anderen Reviewer, ich hab doch keine Ahnung und winke nur durch ;_)

**Comment by janrenz** [comment]
will this work with nested urls? maybe add some test for the getPath Function...

**Comment by tofixx** [comment]
> will this work with nested urls? maybe add some test for the getPath Function...

this will cut an url on first occurence of `#` or `?`. how do you mean nested?

**Comment by janrenz** [comment]
Ok, we then should monitor this when introducing new routes

**Pull request merged**
