### PR TITLE
defer execution of calculateMetrix to avoid missing values in window.…

### PR DESCRIPTION
**Pull request by tofixx**
let metrix calculation await all values are avalilable to avoid negative numbers

### CODE REVIEW

**Comment by tofixx** [comment]
@adrianjost  however travis is still failing, how to fix this?
 ```
Homework tests GET /homework/new:
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by adrianjost** [comment]
For me https://schul-cloud.org/homework/new isn't loading at all so there must be a bug and it's correct that the test is failing. But this has nothing Todo with your pull request. Will take a look on this later today!

**Comment by adrianjost** [comment]
This thing broke with a server security update: `UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"name":"NotFound","message":"There are no lessons that you have access to."`

**Comment by adrianjost** [comment]
The failing tests should be fixed here: https://github.com/schul-cloud/schulcloud-client/pull/982

**Pull request closed without merging**
