### PR TITLE
add api catch handler

### PR DESCRIPTION
**Pull request by adrianjost**
Goal: Client is crashing sometimes if the server is not reachable. This adds some catch handlers to handle these cases.

- I definetly missed some errors, but I only adjusted the code where I was sure that it is not breaking anything. Wherever I was sure I have added `.catch(next)`.

- also executed `eslint autofix` where needed, so some files may show a lot of changes. I am Sorry for that!

- related to: https://ticketsystem.schul-cloud.org/browse/SC-3702

## Mehr
Weitere Informationen zur DoD [hier im Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 285
- Added 28
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5216979&bid=17105125)

**Comment by tofixx** [comment]
why not adding the catch into the api() call itself?

**Comment by malcm** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 285
- Added 28
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5216979&bid=17105125)

**Comment by adrianjost** [comment]
> why not adding the catch into the api() call itself?

because next is not available there and we do not want to catch all errors from all api requests. There are some requests that can handle errors totally fine and those routes can continue working, even if one of the requests failed.

**Comment by CeEv** [comment]
@adrianjost Konflik

**Comment by adrianjost** [comment]
@CeEv conflicts resolved and mocha is now green. I had introduced a small bug that nocha catched. It's now fixed.

**Pull request merged**
