### PR TITLE
[SC-4980] Hilfebereich as a menu point on the left side

### PR DESCRIPTION
**Pull request by qnowak**
# Description
User want to see the 'Hilfebereich' including all sub-pages within the left menu.

## Links to Tickets or other pull requests
- https://ticketsystem.schul-cloud.org/browse/SC-4980

## Changes
- Added new items to side menu
- Added new pages (help and help/contact)
- Changed path to page from /help to /help/article

## Screenshots of UI changes
 - Contact page
screencapture-localhost-3100-help-contact-2020-06-29-10_11_46
- Help/article page
screencapture-localhost-3100-help-articles-2020-06-29-10_12_41
- Help page / Hilfebereich
screencapture-localhost-3100-help-2020-06-29-15_13_26

## Approval for review
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

### CODE REVIEW

**Comment by BlackGhostHD** [comment]
Should this PR be reviewed? If so, can you please provide screenshots and set the label?

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5756123&bid=18842483)

**Comment by Parnswir** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/schul-cloud/schulcloud-client/pullRequest?prid=5756123&bid=18842483)

**Comment by seulki-lee-cloud** [comment]
@qnowak could you please check rocket chat? there is updated info

**Comment by BlackGhostHD** [comment]
⚠️ missing for nuxt ⚠️

**Pull request merged**
